name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done - bye!"
